name: check

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing GitHub action
    steps:
      - uses: actions/checkout@v2
      - name: uses install-with-cpanm
        uses: ./
      - name: which cpanm
        run: which cpanm
