name: check

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing GitHub action
    steps:
      - name: install-cpanm
        uses: perl-actions/install-cpanm@master
      - name: which cpanm
        run: which cpanm
